language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
    - info@chuda.mi
    - chudacontreras@gmail.com
    on_sussess: always
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-tocken: $GITHUB_TOKEN
  local-dir: dist/
  terget-branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: master
   
